#!/usr/bin/env bash

# Build, and then escalate to root
if [ ! "$UID" -eq 0 ]; then
  nix build || exit
  exec sudo bash "$0" "$@"
fi
echo "Got root privileges..."

deploy() {
  # Wait for a new device to show up
  echo "Waiting for device..."
  dev=$(udevadm monitor -p --subsystem-match block | while read -r line; do
    if dev=$(echo "$line" | grep --perl-regexp --only-matching '/dev/sd.+'); then
      echo "$dev"
      break
    fi
  done)
    
  # Mount and copy firmware
  echo "Got $dev, mounting..."
  mount "$dev" /mnt
  echo "$dev mounted, copying firmware..."
  cp result/glove80.uf2 /mnt
}

# Run it twice because two halves of the keyboard
deploy
echo "First firmware copy complete..."
deploy
echo "Second firmware copy complete."

echo "Done."
